version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  node-app:
    build: .
    image: chriscloudreach/node-app   # this should correspond to dockerhub repo where the image is stored
    environment:
      - PORT=4000
    depends_on:
      - mydb

  mydb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chris
      - MONGO_INITDB_ROOT_PASSWORD=password1

    volumes:
      - mongo_data:/data/db  #named volume

  redis:
    image: redis

volumes:
  mongo_data: 